// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFZ9yGoZCKzrWpglQmRTOOHaWgXxty57w',
    appId: '1:577466012100:web:3e350cfa7a3136c9e41491',
    messagingSenderId: '577466012100',
    projectId: 'mobmart-7f763',
    authDomain: 'mobmart-7f763.firebaseapp.com',
    storageBucket: 'mobmart-7f763.appspot.com',
    measurementId: 'G-F37958MY62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB62B975hNSVoJlcSgRiV0e2dc_TD0F5Z4',
    appId: '1:577466012100:android:22745aaa061c8611e41491',
    messagingSenderId: '577466012100',
    projectId: 'mobmart-7f763',
    storageBucket: 'mobmart-7f763.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKogwEdjwZDIrtvDNZsBleS0C3SC7bAdo',
    appId: '1:577466012100:ios:7f717e6c791997c0e41491',
    messagingSenderId: '577466012100',
    projectId: 'mobmart-7f763',
    storageBucket: 'mobmart-7f763.appspot.com',
    iosBundleId: 'com.example.mobmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKogwEdjwZDIrtvDNZsBleS0C3SC7bAdo',
    appId: '1:577466012100:ios:7f717e6c791997c0e41491',
    messagingSenderId: '577466012100',
    projectId: 'mobmart-7f763',
    storageBucket: 'mobmart-7f763.appspot.com',
    iosBundleId: 'com.example.mobmart',
  );
}
